#!/usr/bin/env python3
"""
Ralph v3 — Project Scaffold Wizard

Generates the full project tree as defined in docs/v3-redesign.md Section 8.
GitHub Issues as ticket store. No local database.

Usage:
    ralph init [project-name]            # Interactive
    ralph init [project-name] --no-input # Non-interactive (defaults)
"""

import os
import subprocess
import sys
from pathlib import Path
from typing import Optional


# ─────────────────────────────────────────────────────────
# Template content — all inline so init.py is self-contained
# ─────────────────────────────────────────────────────────

CONFIG_TOML = """\
# Ralph v3 — Project Configuration
# Generated by ralph init

[ralph]
version = "3.0.0"

[agent]
# AI agent binary: "pi" or "kimi"
binary = "{agent}"

[ticket]
# GitHub repo (owner/repo) — auto-detected from git remote
repo = "{repo}"
# GitHub project number for Kanban board sync (optional).
# Set this to mirror every status label transition to the Project's "Status"
# field, so cards move between Kanban columns automatically.
# Leave commented to disable board sync (labels still update).
{project_line}

[project]
# Name of the single-select field that drives board columns.
status_field = "Status"

# Map Ralph status labels to board column names.
[project.status_map]
"status:ready"   = "Ready"
"status:design"  = "In Progress"
"status:build"   = "In Progress"
"status:verify"  = "In Progress"
"status:review"  = "Review"
"status:blocked" = "Blocked"
"closed"         = "Done"

[validate]
# Default test tier for the loop
default_tier = "{tier}"

# Lint tools to run on modified files
lint_tools = ["black", "isort", "flake8", "mypy"]

[daemon]
# Sleep interval (seconds) when no ready tickets
sleep_interval = 60
"""

PROMPT_MD = """\
# Ralph v3 — Agent Prompt

You are an expert software engineer working inside Ralph, an automated build system.
Your job is to complete the issue described below.

## Rules

1. **Understand first.** Read the issue body thoroughly. Identify what needs to change.
2. **Research the codebase.** Use grep, find, and file reads to understand existing code
   conventions, patterns, and architecture before writing any code.
3. **Write minimal, correct code.** Only change what the issue requires. Follow existing
   patterns. Do not over-engineer.
4. **Write tests.** Every functional change must have corresponding tests. Write unit
   tests for internal logic. Write integration tests where appropriate.
5. **Validate.** Run `ralph validate --tier=targeted` when done. Tests MUST pass.
6. **Do NOT commit or push.** Ralph handles all git commits and pushes at stage boundaries.
   Leave changes in the working tree / index for Ralph to commit.
7. **Do NOT touch GitHub labels or issues.** The orchestrator handles all label transitions.
   Only write code, tests, and documentation.

## The Issue
"""

PROGRESS_MD = """\
# Ralph Progress Log

> Auto-generated by Ralph v3. Tracks agent progress per issue.

---

"""

AGENTS_MD = """\
# AGENTS.md

This repository is managed by **Ralph v3**, an automated build system.

## How Ralph Works

1. A human creates a GitHub Issue with `type:task` and `status:ready` labels.
2. Ralph picks up the issue and runs it through a build pipeline.
3. The agent (pi/kimi) implements the changes, writes tests, and validates.
4. Ralph marks the issue `status:review` for human inspection.

## For Agents

- Read `docs/agent/PROMPT.md` for your base instructions.
- Read `docs/agent/PROGRESS.md` to see what has been done.
- Follow existing code conventions. Look at the codebase before writing.
- Always run `ralph validate` before considering work complete.
- Do NOT modify GitHub labels — the orchestrator handles that.

## Project Layout

```
src/           → Application source
tests/unit/    → Unit tests
tests/integration/ → Integration tests
config/        → Project configuration
docs/          → Documentation
logs/          → Daemon logs (gitignored)
.ralph/        → Ralph state (gitignored)
```
"""

RALPH_PREFLIGHT = """\
#!/usr/bin/env bash
# Ralph v3 — Pre-flight Guardrails
#
# Runs before each agent invocation. Exits 0 to proceed, non-zero to block.
# Customize this file to add project-specific safety checks.
#
# Examples:
#   - Check that API keys are set but not committed
#   - Verify database is running
#   - Ensure required services are available

set -euo pipefail

echo "[RALPH PREFLIGHT] All checks passed."
exit 0
"""

TEST_MAP_YAML = """\
# Ralph v3 — Test Map
# Maps source files to their corresponding test paths.
# Used by `ralph validate --tier=targeted` to run only affected tests.
#
# Format:
#   mappings:
#     - source: "src/my_project/module.py"
#       tests: ["tests/unit/test_module.py"]
#
#   default_tests:
#     - "tests/unit/"
#
# When no source files match, default_tests are run.

mappings: []

default_tests:
  - "tests/unit/"
"""

GITIGNORE_CONTENT = """\
# Ralph v3
.ralph/
logs/
*.log

# Python
__pycache__/
*.pyc
*.pyo
*.egg-info/
dist/
build/
.venv/
venv/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
"""


DESIGN_MD = """\
# Ralph v3 — DESIGN Stage Prompt

You are a **systems architect**. Your job is to understand the issue,
research the codebase, and produce a design spec. Do NOT write implementation
code or tests.

## Process

1. **Read the issue** thoroughly. Identify what needs to change.
2. **Research the codebase.** Understand existing patterns, file layout,
   dependencies, and coupling surfaces.
3. **Surface assumptions.** What are you assuming? What needs clarification?
4. **Define success criteria.** What does "done" look like?
5. **Produce a design spec** in `docs/agent/PROGRESS.md`.

## Design Spec Format

Write your spec in `docs/agent/PROGRESS.md`:

```markdown
# Design Spec: #<issue-number> <title>

## Summary
Brief summary of the change.

## Affected Files
- src/path/to/file.py — what changes
- tests/path/to/test.py — new tests needed

## Design Decisions
1. Decision — why

## Acceptance Criteria
- [ ] Criterion 1
- [ ] Criterion 2

## Risks / Edge Cases
- Risk 1
```

## Rules
- Do NOT write code. This is the design phase only.
- Do NOT write tests. That comes in the BUILD phase.
- Do NOT modify GitHub labels or issues.
- Commit your design spec when done.
"""

BUILD_MD = """\
# Ralph v3 — BUILD Stage Prompt

You are a **developer** building to spec. A design spec exists in
`docs/agent/PROGRESS.md`. Your job is to implement the changes and
write tests that validate them.

## Process

1. **Read the design spec** in `docs/agent/PROGRESS.md`.
2. **Read the issue** to understand the goal.
3. **Write tests first.** Write unit tests and integration tests that
   validate the acceptance criteria from the design spec.
4. **Implement the code.** Write minimal, clean code to make tests pass.
5. **Run validation.** `ralph validate --tier=targeted` must pass.

## Rules
- Follow existing code conventions and patterns.
- Only change what the design spec requires.
- Write unit tests for all new internal logic.
- Write integration tests where appropriate.
- Tests MUST pass before you commit.
- Do NOT modify GitHub labels or issues.
- Commit working slices as you go.
"""

VERIFY_MD = """\
# Ralph v3 — VERIFY Stage Prompt (Mode A — Isolated Sub-Agent)

You are an **independent reviewer sub-agent**. You are running in a FRESH session
with no prior knowledge of the codebase or implementation. You did not write the
code. Your only context is: the original issue, the design spec, and the git diff.

This isolation is deliberate — it prevents you from "marking your own homework."

## Process

1. **Read the original issue** — what was requested?
2. **Read the design spec** (provided below) — what was planned?
3. **Review the git diff** (provided below) — what was actually changed?
4. **Do a 5-axis review:**
   - **Correctness:** Does it do what the issue asked?
   - **Simplicity:** Is the solution minimal? No over-engineering?
   - **Tests:** Do tests exist and cover the acceptance criteria?
   - **Security:** Any new attack surfaces or data leaks?
   - **Maintainability:** Is the code clear, documented, following conventions?
5. **Run the validation gate:** `ralph validate --tier=targeted`
6. **Report pass/fail** per acceptance criterion.

## Output Format

```markdown
# Review: #<issue-number>

## Acceptance Criteria
- [x] Criterion 1 — PASS
- [x] Criterion 2 — PASS

## 5-Axis Review
- Correctness: PASS/FAIL — reason
- Simplicity: PASS/FAIL — reason
- Tests: PASS/FAIL — reason
- Security: PASS/FAIL — reason
- Maintainability: PASS/FAIL — reason

## Overall: PASS / FAIL
```

## Rules
- Be critical. Flag issues even if small.
- If any acceptance criterion fails, overall is FAIL.
- Do NOT modify code — this is review only.
- Do NOT modify GitHub labels or issues.
- Do NOT read the codebase — your review is based on the diff provided.
"""

TEST_MD = """\
# Ralph v3 — TEST Sub-Agent Prompt (Mode A — Isolated)

You are a **QA engineer sub-agent** running in a FRESH, isolated session.
You have NO knowledge of the codebase. You see ONLY the design spec and
the original issue. You do NOT see any implementation code.

This isolation is deliberate — you write tests purely from the specification,
ensuring genuine independent testing. Tests should fail because no
implementation exists yet.

## Process

1. **Read the original issue** — what is being built or fixed?
2. **Read the design spec** (provided below) — what was designed?
3. **Identify every acceptance criterion** in the design spec.
4. **Write tests** that validate each acceptance criterion.
   - Map each criterion to at least one test.
   - Write unit tests for internal logic boundaries.
   - Write integration tests where the design spec crosses module boundaries.
   - Edge cases: null/empty inputs, boundary values, error paths.
5. **Tests SHOULD FAIL** — there is no implementation yet. That is expected.
   If a test accidentally passes, it's too weak. Make it meaningfully test the spec.

## Test Placement

- Unit tests → `tests/unit/test_<module>.py`
- Integration tests → `tests/integration/test_<feature>.py`
- Follow the project's existing test conventions (pytest, unittest, etc.)

## Rules
- Do NOT look at any existing implementation code. You are testing from spec ONLY.
- Do NOT write implementation code. Your job is tests only.
- Do NOT modify GitHub labels or issues.
- Document each test with a brief comment linking it to an acceptance criterion.
- Use descriptive test names that explain what is being tested and expected.
"""

IMPLEMENT_MD = """\
# Ralph v3 — IMPLEMENT Sub-Agent Prompt (Mode B — Context Inherit)

You are a **developer sub-agent** continuing from the DESIGN session.
You inherit full codebase knowledge, design decisions, and context from
the architect who researched the codebase. You are NOT starting fresh.

An independent QA sub-agent (Mode A, isolated) has already written tests.
The QA agent never saw the codebase — tests were written purely from spec.
They should be genuinely failing right now because no implementation exists.

Your job: find the test files, write minimal implementation code to make
them pass, plus unit tests for internal logic the QA may have missed.

## Process

1. **You already know the codebase** from the DESIGN session. Use that knowledge.
2. **Find the test files** — they are in tests/ directory, written by QA.
   Read them to understand what they expect.
3. **Implement the code.** Write minimal, clean code to make tests pass:
   - Follow existing code conventions exactly.
   - Only change what the design spec requires (you have it in session memory).
   - Do NOT modify test files (except for import/compilation fixes).
   - The tests are the truth — your code must satisfy them.
4. **Write unit tests for internal logic** that QA tests don't cover:
   - Private helper functions
   - Internal state transitions
   - Error handling branches
5. **Run tests:** execute the test suite with pytest. All tests must pass.
6. **Run validation:** `ralph validate --tier=targeted` must pass.

## Rules
- Follow existing code conventions and patterns.
- Only change what the design spec requires — no scope creep.
- Do NOT modify test files except for import/compilation fixes.
- Tests MUST pass before you consider work done.
- Do NOT modify GitHub labels or issues.
- Commit working slices as you go.
"""


# ─────────────────────────────────────────────────────────
# Scaffold logic
# ─────────────────────────────────────────────────────────

def write_file(path: Path, content: str, executable: bool = False):
    """Write content to a file, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.lstrip("\n"))
    if executable:
        path.chmod(0o755)


def scaffold(project_dir: Path, repo: str = "owner/repo",
              agent: str = "pi", tier: str = "targeted",
              project_number: Optional[int] = None):
    """Generate the full Ralph v3 project scaffold."""

    print(f"Scaffolding Ralph v3 project at: {project_dir}")
    print()

    # ── DIRECTORIES ──────────────────────────────────────
    dirs = [
        ".ralph",
        "config",
        "docs/agent/prompts",
        "logs",
        "src",
        "tests/unit",
        "tests/integration",
    ]
    for d in dirs:
        full = project_dir / d
        full.mkdir(parents=True, exist_ok=True)
        print(f"  ✓  {d}/")

    # ── ROOT FILES ───────────────────────────────────────
    write_file(project_dir / "AGENTS.md", AGENTS_MD)
    print("  ✓  AGENTS.md")

    write_file(project_dir / ".gitignore", GITIGNORE_CONTENT)
    print("  ✓  .gitignore")

    # ── .ralph/ ──────────────────────────────────────────
    project_line = f"project = {project_number}" if project_number else "# project = 1"
    write_file(project_dir / ".ralph" / "config.toml",
               CONFIG_TOML.replace("{repo}", repo)
                          .replace("{agent}", agent)
                          .replace("{tier}", tier)
                          .replace("{project_line}", project_line))
    print("  ✓  .ralph/config.toml")

    # ── config/ ──────────────────────────────────────────
    write_file(project_dir / "config" / "ralph_preflight.sh",
               RALPH_PREFLIGHT, executable=True)
    print("  ✓  config/ralph_preflight.sh")

    write_file(project_dir / "config" / "TEST_MAP.yaml", TEST_MAP_YAML)
    print("  ✓  config/TEST_MAP.yaml")

    # ── docs/agent/ ──────────────────────────────────────
    write_file(project_dir / "docs" / "agent" / "PROMPT.md", PROMPT_MD)
    print("  ✓  docs/agent/PROMPT.md")

    write_file(project_dir / "docs" / "agent" / "PROGRESS.md", PROGRESS_MD)
    print("  ✓  docs/agent/PROGRESS.md")

    # Phase 2+: persona prompts for each stage
    prompt_contents = {
        "design.md": DESIGN_MD,
        "build.md": BUILD_MD,
        "verify.md": VERIFY_MD,
        "test.md": TEST_MD,
        "implement.md": IMPLEMENT_MD,
        "feature.md": "",
        "bugfix.md": "",
        "docs.md": "",
    }
    for name, content in prompt_contents.items():
        p = project_dir / "docs" / "agent" / "prompts" / name
        if content:
            write_file(p, content)
        else:
            p.touch()
        print(f"  ✓  docs/agent/prompts/{name}")

    # ── logs/ ────────────────────────────────────────────
    write_file(project_dir / "logs" / "ralph_daemon.log", "")
    print("  ✓  logs/ralph_daemon.log")

    write_file(project_dir / "logs" / "ralph_metrics.jsonl", "")
    print("  ✓  logs/ralph_metrics.jsonl")

    # ── placeholders ─────────────────────────────────────
    (project_dir / "src" / ".gitkeep").touch()
    (project_dir / "tests" / "unit" / ".gitkeep").touch()
    (project_dir / "tests" / "integration" / ".gitkeep").touch()
    print("  ✓  src/ (placeholder)")
    print("  ✓  tests/unit/ (placeholder)")
    print("  ✓  tests/integration/ (placeholder)")

    print()
    print("Project scaffold complete!")
    print()
    if project_dir.resolve() != Path.cwd():
        print(f"  cd {project_dir.name}")
    print("  ralph setup")
    print("  ralph daemon")
    print()


# ─────────────────────────────────────────────────────────
# Detection helpers
# ─────────────────────────────────────────────────────────

def _detect_project_name(project_dir: Path) -> str:
    """Infer a project name from the directory name."""
    name = project_dir.resolve().name
    # Sanitize: lowercase, replace spaces/special chars with hyphens
    import re
    name = re.sub(r'[^a-zA-Z0-9_-]', '-', name).strip('-')
    return name or "my-project"


def _extract_repo_from_url(url: str) -> str | None:
    """Extract owner/repo from a git remote URL."""
    for prefix in ["https://github.com/", "git@github.com:"]:
        if url.startswith(prefix):
            path = url[len(prefix):]
            if path.endswith(".git"):
                path = path[:-4]
            return path
    return None


def _detect_repo(project_dir: Path) -> str:
    """Try to detect the GitHub repo from git remote."""
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, cwd=project_dir
        )
        if result.returncode == 0:
            repo = _extract_repo_from_url(result.stdout.strip())
            if repo:
                return repo
    except Exception:
        pass
    return "owner/repo"


def _detect_agent() -> str:
    """Check which AI agents are available."""
    for agent in ["pi", "kimi"]:
        if subprocess.run(["which", agent], capture_output=True).returncode == 0:
            return agent
    return "pi"  # default


def _prompt(prompt: str, default: str, yes: bool = False) -> str:
    """Ask the user a question, return their answer or the default."""
    if yes:
        print(f"{prompt} [{default}]: {default}")
        return default
    try:
        answer = input(f"{prompt} [{default}]: ").strip()
        return answer if answer else default
    except (EOFError, KeyboardInterrupt):
        print()
        return default


def _confirm(prompt: str, default: bool = True, yes: bool = False) -> bool:
    """Ask a yes/no question. Returns True/False."""
    yn = "Y/n" if default else "y/N"
    if yes:
        print(f"{prompt} [{yn}]: {'Y' if default else 'N'}")
        return default
    try:
        answer = input(f"{prompt} [{yn}]: ").strip().lower()
        if not answer:
            return default
        return answer in ("y", "yes")
    except (EOFError, KeyboardInterrupt):
        print()
        return default


def _init_git(project_dir: Path):
    """Initialize a git repository and commit the scaffold."""
    try:
        subprocess.run(["git", "init"], cwd=project_dir,
                       capture_output=True, check=True)
        subprocess.run(["git", "add", "-A"], cwd=project_dir,
                       capture_output=True, check=True)
        subprocess.run(
            ["git", "commit", "-m", "ralph init"],
            cwd=project_dir, capture_output=True, check=True
        )
        print("  ✓  git init && git commit 'ralph init'")
    except subprocess.CalledProcessError as e:
        print(f"  ⚠  git init failed: {e.stderr.strip() if e.stderr else e}")
        print("     You can initialize git manually:")
        print("       git init && git add -A && git commit -m 'ralph init'")


# ─────────────────────────────────────────────────────────
# GitHub label creation
# ─────────────────────────────────────────────────────────

RALPH_LABELS = [
    # Status labels (Ralph manages these)
    ("status:ready", "0E8A16", "Ready to be picked up by the build pipeline"),
    ("status:design", "1D76DB", "In design stage — agent researching and writing spec"),
    ("status:build", "0052CC", "In build stage — agent implementing changes"),
    ("status:verify", "5319E7", "In verify stage — independent review running"),
    ("status:review", "D4C5F9", "Awaiting human review"),
    ("status:blocked", "B60205", "Cannot proceed — needs human intervention"),
    # Type labels (set by human)
    ("type:task", "0E8A16", "Work ticket"),
    ("type:bug", "D73A4A", "Bug fix"),
    ("type:feature", "0075CA", "Feature container"),
    ("type:epic", "3F2D7E", "Epic container"),
    ("type:exit", "FBCA04", "Exit / integration ticket"),
    # Phase labels (set by human)
    ("phase:1", "F9D0C4", "Phase 1"),
    ("phase:2", "FEF2C0", "Phase 2"),
    ("phase:3", "C2E0C6", "Phase 3"),
    # Priority labels (optional)
    ("priority:1", "D93F0B", "Critical priority"),
    ("priority:2", "E99695", "High priority"),
    ("priority:3", "F9D0C4", "Medium priority"),
]


def _create_labels(repo: str) -> tuple[int, int]:
    """Create all Ralph labels on the GitHub repo.
    Returns (created, skipped) counts."""
    import json
    # Get existing labels
    try:
        result = subprocess.run(
            ["gh", "label", "list", "--repo", repo, "--json", "name"],
            capture_output=True, text=True
        )
        existing = {l["name"] for l in json.loads(result.stdout)}
    except Exception:
        existing = set()

    created = 0
    skipped = 0
    for name, color, desc in RALPH_LABELS:
        if name in existing:
            skipped += 1
            continue
        try:
            subprocess.run(
                ["gh", "label", "create", name,
                 "--color", color,
                 "--description", desc,
                 "--repo", repo],
                capture_output=True, check=True
            )
            created += 1
            print(f"  ✓  {name}")
        except subprocess.CalledProcessError as e:
            print(f"  ✗  {name} — {e.stderr.strip() if e.stderr else 'failed'}")

    return created, skipped


# ─────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────

def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Scaffold a new Ralph v3 project",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  ralph init                  Init current directory (interactive)
  ralph init my-project       Create and init a new directory (interactive)
  ralph init . --yes          Init current directory with all defaults
  ralph init . --yes --create-labels   Also create GitHub labels
  ralph init . --yes --github-project 5   Enable board sync for project #5
        """)
    parser.add_argument(
        "name", nargs="?", default=None,
        help="Project name or path (default: current directory)")
    parser.add_argument(
        "--yes", "-y", "--no-input", action="store_true",
        help="Non-interactive: use all defaults, skip prompts")
    parser.add_argument(
        "--create-labels", action="store_true",
        help="Create Ralph labels on the GitHub repo")
    parser.add_argument(
        "--agent", choices=["pi", "kimi"], default=None,
        help="AI agent to use (default: auto-detected)")
    parser.add_argument(
        "--tier", choices=["smoke", "targeted", "integration", "full"],
        default=None, help="Default test tier (default: targeted)")
    parser.add_argument(
        "--github-project", type=int, default=None, metavar="N",
        help="Enable GitHub Project board sync for project number N")

    args = parser.parse_args()

    # ── Determine project directory ──
    if args.name is None or args.name == ".":
        project_dir = Path.cwd()
        project_name = _detect_project_name(project_dir)
        creating_new = False
    else:
        project_dir = Path(args.name).resolve()
        project_name = args.name.rstrip("/")
        creating_new = not project_dir.exists()

    # ── Validate directory ──
    if project_dir.exists():
        if not project_dir.is_dir():
            print(f"Error: '{project_dir}' exists and is not a directory.")
            return 1
        # Allow non-empty dirs in interactive mode (warn but proceed)
        contents = list(project_dir.iterdir())
        # Filter out .git and .ralph (already initialized)
        non_ralph = [c for c in contents
                     if c.name not in (".git", ".ralph", ".gitignore", "AGENTS.md")]
        if non_ralph and not args.yes:
            print(f"Directory '{project_dir}' is not empty ({len(non_ralph)} items).")
            print("Ralph will add its files alongside existing content.")
            if not _confirm("Continue?", default=True):
                print("Cancelled.")
                return 1

    project_dir.mkdir(parents=True, exist_ok=True)

    # ── Collect configuration ──
    print()
    print("╔══════════════════════════════════════════╗")
    print("║   Ralph v3 — Project Setup Wizard        ║")
    print("╚══════════════════════════════════════════╝")
    print()

    # Repo detection
    repo = _detect_repo(project_dir)
    if repo == "owner/repo" and creating_new:
        # Guess from directory name + gh auth user
        try:
            user_result = subprocess.run(
                ["gh", "api", "user", "--jq", ".login"],
                capture_output=True, text=True
            )
            if user_result.returncode == 0:
                user = user_result.stdout.strip()
                repo = f"{user}/{project_name}"
        except Exception:
            pass

    repo = _prompt("GitHub repo (owner/name)", repo, yes=args.yes)

    # Agent detection
    agent = args.agent or _detect_agent()
    agent = _prompt("AI agent", agent, yes=args.yes)

    # Test tier
    tier = args.tier or "targeted"
    tier = _prompt("Default test tier", tier, yes=args.yes)

    # ── GitHub Project board sync ──
    project_number = None
    if args.github_project is not None:
        project_number = args.github_project
    elif not args.yes:
        if _confirm("Enable GitHub Project board sync?", default=False):
            while True:
                answer = _prompt("GitHub project number", "", yes=False).strip()
                if not answer:
                    project_number = None
                    break
                try:
                    project_number = int(answer)
                    if project_number <= 0:
                        print("Project number must be positive.")
                        continue
                    break
                except ValueError:
                    print("Please enter a valid integer project number.")

    print()

    # ── GitHub labels ──
    if args.create_labels:
        do_labels = True
    elif args.yes:
        do_labels = False
    else:
        do_labels = _confirm("Create Ralph labels on GitHub?", default=True)

    if do_labels and repo != "owner/repo":
        print()
        print(f"Creating labels on {repo}...")
        created, skipped = _create_labels(repo)
        if skipped:
            print(f"  ({skipped} already existed)")
        print(f"  ✓  {created} labels created")
        print()
    elif do_labels:
        print("  ⚠  Skipping labels — no valid repo detected.")
        print("     Run 'ralph setup' after setting up your remote.")
        print()

    # ── Scaffold ──
    scaffold(project_dir, repo, agent=agent, tier=tier,
             project_number=project_number)

    # ── Git init (if not already a repo) ──
    if not (project_dir / ".git").exists():
        do_git = args.yes or _confirm("Initialize git repository?", default=True)
        if do_git:
            print()
            _init_git(project_dir)

    return 0


if __name__ == "__main__":
    sys.exit(main())
