#!/usr/bin/env python3
"""
Ralph v3 — Project Scaffold Wizard

Generates the full project tree as defined in docs/v3-redesign.md Section 8.
Zero beads references. GitHub Issues as ticket store.

Usage:
    ralph init [project-name]            # Interactive
    ralph init [project-name] --no-input # Non-interactive (defaults)
"""

import os
import sys
from pathlib import Path


# ─────────────────────────────────────────────────────────
# Template content — all inline so init.py is self-contained
# ─────────────────────────────────────────────────────────

CONFIG_TOML = """\
# Ralph v3 — Project Configuration
# Generated by ralph init

[ralph]
version = "3.0.0"

[agent]
# AI agent binary: "pi" or "kimi"
binary = "pi"

[ticket]
# GitHub repo (owner/repo) — auto-detected from git remote
repo = "{repo}"

[validate]
# Default test tier for the loop
default_tier = "targeted"

# Lint tools to run on modified files
lint_tools = ["black", "isort", "flake8", "mypy"]

[daemon]
# Sleep interval (seconds) when no ready tickets
sleep_interval = 60
"""

PROMPT_MD = """\
# Ralph v3 — Agent Prompt

You are an expert software engineer working inside Ralph, an automated build system.
Your job is to complete the issue described below.

## Rules

1. **Understand first.** Read the issue body thoroughly. Identify what needs to change.
2. **Research the codebase.** Use grep, find, and file reads to understand existing code
   conventions, patterns, and architecture before writing any code.
3. **Write minimal, correct code.** Only change what the issue requires. Follow existing
   patterns. Do not over-engineer.
4. **Write tests.** Every functional change must have corresponding tests. Write unit
   tests for internal logic. Write integration tests where appropriate.
5. **Validate.** Run `ralph validate --tier=targeted` when done. Tests MUST pass.
6. **Commit.** Commit your changes with a descriptive message referencing the issue number.
7. **Do NOT touch GitHub labels or issues.** The orchestrator handles all label transitions.
   Only write code, tests, and documentation.

## The Issue
"""

PROGRESS_MD = """\
# Ralph Progress Log

> Auto-generated by Ralph v3. Tracks agent progress per issue.

---

"""

AGENTS_MD = """\
# AGENTS.md

This repository is managed by **Ralph v3**, an automated build system.

## How Ralph Works

1. A human creates a GitHub Issue with `type:task` and `status:ready` labels.
2. Ralph picks up the issue and runs it through a build pipeline.
3. The agent (pi/kimi) implements the changes, writes tests, and validates.
4. Ralph marks the issue `status:review` for human inspection.

## For Agents

- Read `docs/agent/PROMPT.md` for your base instructions.
- Read `docs/agent/PROGRESS.md` to see what has been done.
- Follow existing code conventions. Look at the codebase before writing.
- Always run `ralph validate` before considering work complete.
- Do NOT modify GitHub labels — the orchestrator handles that.

## Project Layout

```
src/           → Application source
tests/unit/    → Unit tests
tests/integration/ → Integration tests
config/        → Project configuration
docs/          → Documentation
logs/          → Daemon logs (gitignored)
.ralph/        → Ralph state (gitignored)
```
"""

RALPH_PREFLIGHT = """\
#!/usr/bin/env bash
# Ralph v3 — Pre-flight Guardrails
#
# Runs before each agent invocation. Exits 0 to proceed, non-zero to block.
# Customize this file to add project-specific safety checks.
#
# Examples:
#   - Check that API keys are set but not committed
#   - Verify database is running
#   - Ensure required services are available

set -euo pipefail

echo "[RALPH PREFLIGHT] All checks passed."
exit 0
"""

TEST_MAP_YAML = """\
# Ralph v3 — Test Map
# Maps source files to their corresponding test paths.
# Used by `ralph validate --tier=targeted` to run only affected tests.
#
# Format:
#   mappings:
#     - source: "src/my_project/module.py"
#       tests: ["tests/unit/test_module.py"]
#
#   default_tests:
#     - "tests/unit/"
#
# When no source files match, default_tests are run.

mappings: []

default_tests:
  - "tests/unit/"
"""

GITIGNORE_CONTENT = """\
# Ralph v3
.ralph/
logs/
*.log

# Python
__pycache__/
*.pyc
*.pyo
*.egg-info/
dist/
build/
.venv/
venv/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
"""


DESIGN_MD = """\
# Ralph v3 — DESIGN Stage Prompt

You are a **systems architect**. Your job is to understand the issue,
research the codebase, and produce a design spec. Do NOT write implementation
code or tests.

## Process

1. **Read the issue** thoroughly. Identify what needs to change.
2. **Research the codebase.** Understand existing patterns, file layout,
   dependencies, and coupling surfaces.
3. **Surface assumptions.** What are you assuming? What needs clarification?
4. **Define success criteria.** What does "done" look like?
5. **Produce a design spec** in `docs/agent/PROGRESS.md`.

## Design Spec Format

Write your spec in `docs/agent/PROGRESS.md`:

```markdown
# Design Spec: #<issue-number> <title>

## Summary
Brief summary of the change.

## Affected Files
- src/path/to/file.py — what changes
- tests/path/to/test.py — new tests needed

## Design Decisions
1. Decision — why

## Acceptance Criteria
- [ ] Criterion 1
- [ ] Criterion 2

## Risks / Edge Cases
- Risk 1
```

## Rules
- Do NOT write code. This is the design phase only.
- Do NOT write tests. That comes in the BUILD phase.
- Do NOT modify GitHub labels or issues.
- Commit your design spec when done.
"""

BUILD_MD = """\
# Ralph v3 — BUILD Stage Prompt

You are a **developer** building to spec. A design spec exists in
`docs/agent/PROGRESS.md`. Your job is to implement the changes and
write tests that validate them.

## Process

1. **Read the design spec** in `docs/agent/PROGRESS.md`.
2. **Read the issue** to understand the goal.
3. **Write tests first.** Write unit tests and integration tests that
   validate the acceptance criteria from the design spec.
4. **Implement the code.** Write minimal, clean code to make tests pass.
5. **Run validation.** `ralph validate --tier=targeted` must pass.

## Rules
- Follow existing code conventions and patterns.
- Only change what the design spec requires.
- Write unit tests for all new internal logic.
- Write integration tests where appropriate.
- Tests MUST pass before you commit.
- Do NOT modify GitHub labels or issues.
- Commit working slices as you go.
"""

VERIFY_MD = """\
# Ralph v3 — VERIFY Stage Prompt (Mode A — Isolated Sub-Agent)

You are an **independent reviewer sub-agent**. You are running in a FRESH session
with no prior knowledge of the codebase or implementation. You did not write the
code. Your only context is: the original issue, the design spec, and the git diff.

This isolation is deliberate — it prevents you from "marking your own homework."

## Process

1. **Read the original issue** — what was requested?
2. **Read the design spec** (provided below) — what was planned?
3. **Review the git diff** (provided below) — what was actually changed?
4. **Do a 5-axis review:**
   - **Correctness:** Does it do what the issue asked?
   - **Simplicity:** Is the solution minimal? No over-engineering?
   - **Tests:** Do tests exist and cover the acceptance criteria?
   - **Security:** Any new attack surfaces or data leaks?
   - **Maintainability:** Is the code clear, documented, following conventions?
5. **Run the validation gate:** `ralph validate --tier=targeted`
6. **Report pass/fail** per acceptance criterion.

## Output Format

```markdown
# Review: #<issue-number>

## Acceptance Criteria
- [x] Criterion 1 — PASS
- [x] Criterion 2 — PASS

## 5-Axis Review
- Correctness: PASS/FAIL — reason
- Simplicity: PASS/FAIL — reason
- Tests: PASS/FAIL — reason
- Security: PASS/FAIL — reason
- Maintainability: PASS/FAIL — reason

## Overall: PASS / FAIL
```

## Rules
- Be critical. Flag issues even if small.
- If any acceptance criterion fails, overall is FAIL.
- Do NOT modify code — this is review only.
- Do NOT modify GitHub labels or issues.
- Do NOT read the codebase — your review is based on the diff provided.
"""

TEST_MD = """\
# Ralph v3 — TEST Sub-Agent Prompt (Mode A — Isolated)

You are a **QA engineer sub-agent** running in a FRESH, isolated session.
You have NO knowledge of the codebase. You see ONLY the design spec and
the original issue. You do NOT see any implementation code.

This isolation is deliberate — you write tests purely from the specification,
ensuring genuine independent testing. Tests should fail because no
implementation exists yet.

## Process

1. **Read the original issue** — what is being built or fixed?
2. **Read the design spec** (provided below) — what was designed?
3. **Identify every acceptance criterion** in the design spec.
4. **Write tests** that validate each acceptance criterion.
   - Map each criterion to at least one test.
   - Write unit tests for internal logic boundaries.
   - Write integration tests where the design spec crosses module boundaries.
   - Edge cases: null/empty inputs, boundary values, error paths.
5. **Tests SHOULD FAIL** — there is no implementation yet. That is expected.
   If a test accidentally passes, it's too weak. Make it meaningfully test the spec.

## Test Placement

- Unit tests → `tests/unit/test_<module>.py`
- Integration tests → `tests/integration/test_<feature>.py`
- Follow the project's existing test conventions (pytest, unittest, etc.)

## Rules
- Do NOT look at any existing implementation code. You are testing from spec ONLY.
- Do NOT write implementation code. Your job is tests only.
- Do NOT modify GitHub labels or issues.
- Document each test with a brief comment linking it to an acceptance criterion.
- Use descriptive test names that explain what is being tested and expected.
"""

IMPLEMENT_MD = """\
# Ralph v3 — IMPLEMENT Sub-Agent Prompt (Mode B — Full Context)

You are a **developer sub-agent** building to spec. The design spec and tests
already exist. Tests were written by an independent QA sub-agent who never saw
the codebase — they should be genuinely failing right now.

Your job: write minimal implementation code to make those tests pass, plus
unit tests for any internal logic the QA tests may have missed.

## Process

1. **Read the design spec** (provided below). Understand what was planned.
2. **Read the test files** that the QA sub-agent wrote. Understand what they expect.
3. **Research the codebase.** Use grep, find, and file reads to understand:
   - Existing code conventions and patterns
   - File layout and module structure
   - Dependencies and coupling surfaces
   - SDK/API usage patterns already in the codebase
4. **Implement the code.** Write minimal, clean code to make the tests pass:
   - Follow existing code conventions exactly.
   - Only change what the design spec requires.
   - Do NOT modify the test files (except for import/compilation fixes).
   - The tests are the truth — your code must satisfy them.
5. **Write unit tests for internal logic** that the QA tests don't cover:
   - Private helper functions
   - Internal state transitions
   - Error handling branches
6. **Run tests:** execute the test suite with pytest. All tests must pass.
7. **Run validation:** `ralph validate --tier=targeted` must pass.

## Rules
- Follow existing code conventions and patterns.
- Only change what the design spec requires — no scope creep.
- Do NOT modify test files except for import/compilation fixes.
- Tests MUST pass before you consider work done.
- Do NOT modify GitHub labels or issues.
- Commit working slices as you go.
"""


# ─────────────────────────────────────────────────────────
# Scaffold logic
# ─────────────────────────────────────────────────────────

def write_file(path: Path, content: str, executable: bool = False):
    """Write content to a file, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.lstrip("\n"))
    if executable:
        path.chmod(0o755)


def scaffold(project_dir: Path, repo: str = "owner/repo"):
    """Generate the full Ralph v3 project scaffold."""

    print(f"Scaffolding Ralph v3 project at: {project_dir}")
    print()

    # ── DIRECTORIES ──────────────────────────────────────
    dirs = [
        ".ralph",
        "config",
        "docs/agent/prompts",
        "logs",
        "src",
        "tests/unit",
        "tests/integration",
    ]
    for d in dirs:
        full = project_dir / d
        full.mkdir(parents=True, exist_ok=True)
        print(f"  ✓  {d}/")

    # ── ROOT FILES ───────────────────────────────────────
    write_file(project_dir / "AGENTS.md", AGENTS_MD)
    print("  ✓  AGENTS.md")

    write_file(project_dir / ".gitignore", GITIGNORE_CONTENT)
    print("  ✓  .gitignore")

    # ── .ralph/ ──────────────────────────────────────────
    write_file(project_dir / ".ralph" / "config.toml",
               CONFIG_TOML.replace("{repo}", repo))
    print("  ✓  .ralph/config.toml")

    # ── config/ ──────────────────────────────────────────
    write_file(project_dir / "config" / "ralph_preflight.sh",
               RALPH_PREFLIGHT, executable=True)
    print("  ✓  config/ralph_preflight.sh")

    write_file(project_dir / "config" / "TEST_MAP.yaml", TEST_MAP_YAML)
    print("  ✓  config/TEST_MAP.yaml")

    # ── docs/agent/ ──────────────────────────────────────
    write_file(project_dir / "docs" / "agent" / "PROMPT.md", PROMPT_MD)
    print("  ✓  docs/agent/PROMPT.md")

    write_file(project_dir / "docs" / "agent" / "PROGRESS.md", PROGRESS_MD)
    print("  ✓  docs/agent/PROGRESS.md")

    # Phase 2+: persona prompts for each stage
    prompt_contents = {
        "design.md": DESIGN_MD,
        "build.md": BUILD_MD,
        "verify.md": VERIFY_MD,
        "test.md": TEST_MD,
        "implement.md": IMPLEMENT_MD,
        "feature.md": "",
        "bugfix.md": "",
        "docs.md": "",
    }
    for name, content in prompt_contents.items():
        p = project_dir / "docs" / "agent" / "prompts" / name
        if content:
            write_file(p, content)
        else:
            p.touch()
        print(f"  ✓  docs/agent/prompts/{name}")

    # ── logs/ ────────────────────────────────────────────
    write_file(project_dir / "logs" / "ralph_daemon.log", "")
    print("  ✓  logs/ralph_daemon.log")

    write_file(project_dir / "logs" / "ralph_metrics.jsonl", "")
    print("  ✓  logs/ralph_metrics.jsonl")

    # ── placeholders ─────────────────────────────────────
    (project_dir / "src" / ".gitkeep").touch()
    (project_dir / "tests" / "unit" / ".gitkeep").touch()
    (project_dir / "tests" / "integration" / ".gitkeep").touch()
    print("  ✓  src/ (placeholder)")
    print("  ✓  tests/unit/ (placeholder)")
    print("  ✓  tests/integration/ (placeholder)")

    print()
    print("Project scaffold complete!")
    print()
    print("Next steps:")
    print("  1. cd", project_dir.name if project_dir.resolve() != Path.cwd() else ".")
    print("  2. git init && git add -A && git commit -m 'ralph init'")
    print("  3. ralph setup")
    print("  4. ralph daemon")
    print()


# ─────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────

def main() -> int:
    project_name = None

    # Parse args
    args = sys.argv[1:]
    interactive = True
    for a in args:
        if a == "--no-input":
            interactive = False
        elif not a.startswith("--"):
            project_name = a

    # Interactive: ask for project name
    if interactive and project_name is None:
        try:
            project_name = input("Project name: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nCancelled.")
            return 1

    if not project_name:
        print("Usage: ralph init <project-name> [--no-input]")
        return 1

    project_dir = Path(project_name).resolve()
    if project_dir.exists():
        if not project_dir.is_dir():
            print(f"Error: {project_name} exists and is not a directory.")
            return 1
        contents = list(project_dir.iterdir())
        if contents:
            if interactive:
                overwrite = input(
                    f"Directory {project_name} is not empty. Overwrite? [y/N]: "
                ).strip().lower()
                if overwrite != "y":
                    print("Cancelled.")
                    return 1
            else:
                print(f"Error: {project_name} is not empty. Use --no-input only on empty dirs.")
                return 1

    project_dir.mkdir(parents=True, exist_ok=True)

    # Detect repo from git remote (if in a git repo)
    repo = "owner/repo"
    try:
        import subprocess
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, cwd=project_dir
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            # Extract owner/repo from git URL
            # Supports: https://github.com/owner/repo.git, git@github.com:owner/repo.git
            for prefix in ["https://github.com/", "git@github.com:"]:
                if url.startswith(prefix):
                    path = url[len(prefix):]
                    if path.endswith(".git"):
                        path = path[:-4]
                    repo = path
                    break
    except Exception:
        pass

    scaffold(project_dir, repo)
    return 0


if __name__ == "__main__":
    sys.exit(main())
