#!/usr/bin/env python3
"""
Ralph v3 — Project Scaffold Wizard

Generates the full project tree as defined in docs/v3-redesign.md Section 8.
Zero beads references. GitHub Issues as ticket store.

Usage:
    ralph init [project-name]            # Interactive
    ralph init [project-name] --no-input # Non-interactive (defaults)
"""

import os
import sys
from pathlib import Path


# ─────────────────────────────────────────────────────────
# Template content — all inline so init.py is self-contained
# ─────────────────────────────────────────────────────────

CONFIG_TOML = """\
# Ralph v3 — Project Configuration
# Generated by ralph init

[ralph]
version = "3.0.0"

[agent]
# AI agent binary: "pi" or "kimi"
binary = "pi"

[ticket]
# GitHub repo (owner/repo) — auto-detected from git remote
repo = "{repo}"

[validate]
# Default test tier for the loop
default_tier = "targeted"

# Lint tools to run on modified files
lint_tools = ["black", "isort", "flake8", "mypy"]

[daemon]
# Sleep interval (seconds) when no ready tickets
sleep_interval = 60
"""

PROMPT_MD = """\
# Ralph v3 — Agent Prompt

You are an expert software engineer working inside Ralph, an automated build system.
Your job is to complete the issue described below.

## Rules

1. **Understand first.** Read the issue body thoroughly. Identify what needs to change.
2. **Research the codebase.** Use grep, find, and file reads to understand existing code
   conventions, patterns, and architecture before writing any code.
3. **Write minimal, correct code.** Only change what the issue requires. Follow existing
   patterns. Do not over-engineer.
4. **Write tests.** Every functional change must have corresponding tests. Write unit
   tests for internal logic. Write integration tests where appropriate.
5. **Validate.** Run `ralph validate --tier=targeted` when done. Tests MUST pass.
6. **Commit.** Commit your changes with a descriptive message referencing the issue number.
7. **Do NOT touch GitHub labels or issues.** The orchestrator handles all label transitions.
   Only write code, tests, and documentation.

## The Issue
"""

PROGRESS_MD = """\
# Ralph Progress Log

> Auto-generated by Ralph v3. Tracks agent progress per issue.

---

"""

AGENTS_MD = """\
# AGENTS.md

This repository is managed by **Ralph v3**, an automated build system.

## How Ralph Works

1. A human creates a GitHub Issue with `type:task` and `status:ready` labels.
2. Ralph picks up the issue and runs it through a build pipeline.
3. The agent (pi/kimi) implements the changes, writes tests, and validates.
4. Ralph marks the issue `status:review` for human inspection.

## For Agents

- Read `docs/agent/PROMPT.md` for your base instructions.
- Read `docs/agent/PROGRESS.md` to see what has been done.
- Follow existing code conventions. Look at the codebase before writing.
- Always run `ralph validate` before considering work complete.
- Do NOT modify GitHub labels — the orchestrator handles that.

## Project Layout

```
src/           → Application source
tests/unit/    → Unit tests
tests/integration/ → Integration tests
config/        → Project configuration
docs/          → Documentation
logs/          → Daemon logs (gitignored)
.ralph/        → Ralph state (gitignored)
```
"""

RALPH_PREFLIGHT = """\
#!/usr/bin/env bash
# Ralph v3 — Pre-flight Guardrails
#
# Runs before each agent invocation. Exits 0 to proceed, non-zero to block.
# Customize this file to add project-specific safety checks.
#
# Examples:
#   - Check that API keys are set but not committed
#   - Verify database is running
#   - Ensure required services are available

set -euo pipefail

echo "[RALPH PREFLIGHT] All checks passed."
exit 0
"""

TEST_MAP_YAML = """\
# Ralph v3 — Test Map
# Maps source files to their corresponding test paths.
# Used by `ralph validate --tier=targeted` to run only affected tests.
#
# Format:
#   mappings:
#     - source: "src/my_project/module.py"
#       tests: ["tests/unit/test_module.py"]
#
#   default_tests:
#     - "tests/unit/"
#
# When no source files match, default_tests are run.

mappings: []

default_tests:
  - "tests/unit/"
"""

GITIGNORE_CONTENT = """\
# Ralph v3
.ralph/
logs/
*.log

# Python
__pycache__/
*.pyc
*.pyo
*.egg-info/
dist/
build/
.venv/
venv/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
"""


# ─────────────────────────────────────────────────────────
# Scaffold logic
# ─────────────────────────────────────────────────────────

def write_file(path: Path, content: str, executable: bool = False):
    """Write content to a file, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.lstrip("\n"))
    if executable:
        path.chmod(0o755)


def scaffold(project_dir: Path, repo: str = "owner/repo"):
    """Generate the full Ralph v3 project scaffold."""

    print(f"Scaffolding Ralph v3 project at: {project_dir}")
    print()

    # ── DIRECTORIES ──────────────────────────────────────
    dirs = [
        ".ralph",
        "config",
        "docs/agent/prompts",
        "logs",
        "src",
        "tests/unit",
        "tests/integration",
    ]
    for d in dirs:
        full = project_dir / d
        full.mkdir(parents=True, exist_ok=True)
        print(f"  ✓  {d}/")

    # ── ROOT FILES ───────────────────────────────────────
    write_file(project_dir / "AGENTS.md", AGENTS_MD)
    print("  ✓  AGENTS.md")

    write_file(project_dir / ".gitignore", GITIGNORE_CONTENT)
    print("  ✓  .gitignore")

    # ── .ralph/ ──────────────────────────────────────────
    write_file(project_dir / ".ralph" / "config.toml",
               CONFIG_TOML.replace("{repo}", repo))
    print("  ✓  .ralph/config.toml")

    # ── config/ ──────────────────────────────────────────
    write_file(project_dir / "config" / "ralph_preflight.sh",
               RALPH_PREFLIGHT, executable=True)
    print("  ✓  config/ralph_preflight.sh")

    write_file(project_dir / "config" / "TEST_MAP.yaml", TEST_MAP_YAML)
    print("  ✓  config/TEST_MAP.yaml")

    # ── docs/agent/ ──────────────────────────────────────
    write_file(project_dir / "docs" / "agent" / "PROMPT.md", PROMPT_MD)
    print("  ✓  docs/agent/PROMPT.md")

    write_file(project_dir / "docs" / "agent" / "PROGRESS.md", PROGRESS_MD)
    print("  ✓  docs/agent/PROGRESS.md")

    # Phase 2+ prompt stubs (empty for now, filled in Phase 2/3)
    prompt_stubs = [
        "design.md",
        "test.md",
        "implement.md",
        "verify.md",
        "feature.md",
        "bugfix.md",
        "docs.md",
    ]
    for stub in prompt_stubs:
        p = project_dir / "docs" / "agent" / "prompts" / stub
        p.touch()
        print(f"  ✓  docs/agent/prompts/{stub}")

    # ── logs/ ────────────────────────────────────────────
    write_file(project_dir / "logs" / "ralph_daemon.log", "")
    print("  ✓  logs/ralph_daemon.log")

    write_file(project_dir / "logs" / "ralph_metrics.jsonl", "")
    print("  ✓  logs/ralph_metrics.jsonl")

    # ── placeholders ─────────────────────────────────────
    (project_dir / "src" / ".gitkeep").touch()
    (project_dir / "tests" / "unit" / ".gitkeep").touch()
    (project_dir / "tests" / "integration" / ".gitkeep").touch()
    print("  ✓  src/ (placeholder)")
    print("  ✓  tests/unit/ (placeholder)")
    print("  ✓  tests/integration/ (placeholder)")

    print()
    print("Project scaffold complete!")
    print()
    print("Next steps:")
    print("  1. cd", project_dir.name if project_dir.resolve() != Path.cwd() else ".")
    print("  2. git init && git add -A && git commit -m 'ralph init'")
    print("  3. ralph setup")
    print("  4. ralph daemon")
    print()


# ─────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────

def main() -> int:
    project_name = None

    # Parse args
    args = sys.argv[1:]
    interactive = True
    for a in args:
        if a == "--no-input":
            interactive = False
        elif not a.startswith("--"):
            project_name = a

    # Interactive: ask for project name
    if interactive and project_name is None:
        try:
            project_name = input("Project name: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nCancelled.")
            return 1

    if not project_name:
        print("Usage: ralph init <project-name> [--no-input]")
        return 1

    project_dir = Path(project_name).resolve()
    if project_dir.exists():
        if not project_dir.is_dir():
            print(f"Error: {project_name} exists and is not a directory.")
            return 1
        contents = list(project_dir.iterdir())
        if contents:
            if interactive:
                overwrite = input(
                    f"Directory {project_name} is not empty. Overwrite? [y/N]: "
                ).strip().lower()
                if overwrite != "y":
                    print("Cancelled.")
                    return 1
            else:
                print(f"Error: {project_name} is not empty. Use --no-input only on empty dirs.")
                return 1

    project_dir.mkdir(parents=True, exist_ok=True)

    # Detect repo from git remote (if in a git repo)
    repo = "owner/repo"
    try:
        import subprocess
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, cwd=project_dir
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            # Extract owner/repo from git URL
            # Supports: https://github.com/owner/repo.git, git@github.com:owner/repo.git
            for prefix in ["https://github.com/", "git@github.com:"]:
                if url.startswith(prefix):
                    path = url[len(prefix):]
                    if path.endswith(".git"):
                        path = path[:-4]
                    repo = path
                    break
    except Exception:
        pass

    scaffold(project_dir, repo)
    return 0


if __name__ == "__main__":
    sys.exit(main())
